CI: update yocto targets
After updating CI with Ubuntu 20.04 -> 22.04, the host
python version is now 3.10 which is broken in gatesgarth branch:

"File "/home/qt/work/build/poky/bitbake/lib/bb/persist_data.py", line 22, in <module>
 from collections import Mapping
 ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)"

Also, CI build against master branch has been on hiatus for a while due meta-python2 lacking
layer support for langdale onwards.

Update CI targets by adding LAYERSERIES_COMPAT override for meta-python2 layer to
support newer yocto branches, drop the old EOL yocto branches (gatesgarth, hardknott, honister)
and replace with more recent kirkstone & langdale. Re-enable master branch.

Change-Id: Ia72fb6c45b7a4f489b0e4d5f3512e8a357231d2b
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>
Reviewed-by: Janne Juntunen <janne.juntunen@qt.io>